[package]
name = "linux-command-rust"
version = "0.1.0"
authors = ["ld000 <lidong9144@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
colored = "2"
libc = "0.2"
users = "0.11"
